### ISSUE TITLE
关于安装过程的细节问题

### ISSUE THREAD

**Issue by yiqishangxuequ** [zoeye859/presto_v3_singularity#2]
我在安装过程遇到了一些问题，因为我不太熟悉linux，所以完全是按照流程安装的，最后发现自己在些细节上出了问题。
如果有同样不熟悉linux遇到这些错误的人，或许可以参考一下。

在安装好所有依赖后，再编译presto时，命令行输入make makewisdom，会提示缺少libpng库，所以我又安装了libpng库，在临时环境LD_LIBRARY_PATH中加入了这个库。

输入make makewisdom文件时同时也会提示找不到fftw.h文件，最后我发现，是因为我是完全傻乎乎地按照教程的流程来的。教程中在安装FFTW时，在“./configure --prefix=$ASTROSOFT --enable-float --enable-threads --enable-shared CFLAGS=-fPIC FFLAGS=-fPIC”中使用了ASTROSOFT这个环境变量。而在教程中，ASTROSOFT这个环境变量在下文才被定义，所以在presto的编译中使用make makewisdom会提示找不到fftw.h文件。

之后在执行python tests/test_presto_python.py会提示缺少presto这个库，我本来以为是我安装过程出问题了，最后发现原来直接用python的pip安装这个库就可以了

**Comment by zoeye859** [comment]
It sounds that you chose to install PRESTO by your own. I hope that my experience presented in this repo helped you.

Thank you very much for your feedback!

I updated this container, so that you can also use PSRCHIVE, PSRCAT, DSPSR.

Should you have any enquiries, just let me know. Best of luck!

Zoe
