### ISSUE TITLE
First install Xquartz

### ISSUE THREAD

**Issue by liuzike** [zoeye859/presto_v3_singularity#4]
when you first install XQuartz , you need to  log out your mac  account then log in

**Comment by zoeye859** [comment]
Thank you!

Yes, I forgot to mention this.

"If this is your first time installing XQuartz, you may wish to logout and log back in. This will update your DISPLAY environment variable to point to XQuartz.app rather than X11.app. If you would prefer to keep using X11.app as your default server (you can still launch XQuartz.app manually), you’ll want to disable /Library/LaunchAgents/org.macosforge.xquartz.startx.plist using launchctl(1)."  Quoted from (https://www.xquartz.org/releases/XQuartz-2.7.10.html)
